### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by LeviAckerman1234** [Samoxive/SafetyJim#63]
when i do command not found: --create-slash-commands it says command not found and when i do cargo run --release it says error: could not compile `safetyjim` due to 14 previous errors

**Comment by Samoxive** [comment]
Jim uses development version of serenity library so it always changes, some of these changes are breaking and Jim must be adapted to be built with new version. If you build the project with Cargo.lock versions it should build without problems since it will  use the commit of serenity I last built with.

**Comment by LeviAckerman1234** [comment]
how would i do that? I am kind of new to rust any help is much appreciated

**Comment by LeviAckerman1234** [comment]
could u please help me

**Comment by LeviAckerman1234** [comment]
error: could not compile `safetyjim` due to 14 previous errors also says this when i do cargo build

**Comment by Samoxive** [comment]
You can use `--locked` flag to make cargo use the lock file for dependencies, as this is a personal side project I can't support other people trying to use it themselves, feel free to send a PR if you are willing to contribute but I can't guarantee helping develop Jim in other ways because of time limitations.

**Comment by LeviAckerman1234** [comment]
the code wont compile tho its not gonna work like this

**Comment by Samoxive** [comment]
I have updated the master branch to be compatible with latest serenity commit, you need to use `git pull` to update your local files and use `cargo clean`, then `cargo run --release --locked` to build the project with same dependency versions as me and run it in release mode for best performance.

I have tested these steps on both Windows 11 22H2 and Ubuntu 20.04.4 with Rust 1.64.0 and it works.

You will need to set the following environment variables as Jim no longer uses configuration file. Darksky no longer allows signing up so you can leave it empty, Google geocode and recaptcha tokens can be left empty if you won't use weather command and captcha verification features.

```CORS_ORIGIN=http://localhost:3000
DARKSKY_TOKEN=<darksky_token>
DATABASE_URL=postgres://user:password@host:port/db_name
DISCORD_TOKEN=<discord_token>
GEOCODE_TOKEN=<google_geocode_token>
OAUTH_CLIENT_ID=<discord_client_id>
OAUTH_CLIENT_SECRET=<discord_oauth_secret>
OAUTH_REDIRECT_URI=http://localhost:3000/login
RECAPTCHA_SECRET=<recaptcha_secret>
SELF_URL=http://localhost:8080
SERVER_PORT=8080
SERVER_SECRET=secrekt
```

It is not this project's intention to support people running their own Jim bots or teach Rust, this is all the help you will get running this project.

**Comment by LeviAckerman1234** [comment]
i know its not to teach me or anything but like i keep getting the same errors i am just confused how it works for you lol
